version: "3.8"

services:
  gfas:
    image: gfas
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - eventstoredb
    ports:
      - "127.0.0.1:8088:8088"
    networks:
      - achievement-system

  eventstoredb:
    image: eventstore/eventstore:21.6.0-buster-slim
    user: root
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - ./eventstore/data:/var/lib/eventstore
      - ./eventstore/log:/var/log/eventstore
    networks:
      - achievement-system

networks:
  achievement-system:
    name: "achievement-system"